engine/core/gRenderer.cpp, engine/core/gRenderer.h
=> gRenderer -> gDrawArrow

engine/graphics/gFont.cpp, engine/graphics/gModel.cpp, engine/graphics/gModel.h, engine/graphics/gNode.cpp, engine/graphics/gNode.h
I completed gFont's comments but I need help for correction. If I had a mistake I am waiting for warn from Noyan Culum.
=> gFont's comments added

engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/gFog.cpp, engine/graphics/gFog.h, engine/graphics/gMesh.cpp
=> gFog added

engine/core/gRenderer.cpp, engine/core/gRenderer.h
Draw Rect with boldness option added.
=> gDrawRect with thickness option added.

engine/utils/gDatabase.cpp, engine/utils/gDatabase.h, engine/utils/gLocalization.cpp, engine/utils/gLocalization.h
New methods and functions for gDatabase and gLocalization implanted.
=> getColumnTypes(), getColumnNames(), getTableInfo(), gLocalization added

engine/CMakeLists.txt
=> CMakeList for gLocalization

engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/utils/gDatabase.cpp, engine/utils/gLocalization.cpp, engine/utils/gLocalization.h
gDatabase unnecessary lines deleted and some bug fix.
gLocalization some methods modified, some bug fixed and getColumnList method added.
=> gDatabase and gLocalization unnecessary lines deleted and some bug fix. 

engine/graphics/gRect.cpp, engine/graphics/gRect.h
for gRect class centerX and Y functions added.
=> centerX and Y functions added.

engine/core/gAppManager.cpp, engine/core/gAppManager.h, engine/core/gBaseWindow.cpp, engine/core/gBaseWindow.h, engine/core/gGLFWWindow.cpp, engine/core/gGLFWWindow.h
=> getWindowMode and get/setClipboardString functions added into

engine/CMakeLists.txt, engine/ui/gGUISurface.cpp, engine/ui/gGUISurface.h
2d shapes are done
cmakelist is updated
=> gGUISurface is created

engine/CMakeLists.txt, engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/primitives/gArc.cpp, engine/graphics/primitives/gArc.h, engine/ui/gGUIPieGraph.cpp, engine/ui/gGUIPieGraph.h
gGUIPieGraph and gArc added for pie graph.
=> gGUIPieGraph and gArc added for pie graph.

engine/CMakeLists.txt, engine/ui/gGUITimebox.cpp, engine/ui/gGUITimebox.h
=> The boxes were designed and printed on the screen.
=> Added mousePressed and mouseReleased functions.
=> Added gGUITimebox.h and gGUITimebox.cpp classes

engine/core/gGUIManager.cpp, engine/ui/gGUIDialogue.cpp
=> Added external borders to dialogue box and set dialogue active status by false

engine/CMakeLists.txt, engine/ui/gGUILineGraph.cpp, engine/ui/gGUILineGraph.h
Line graph color can be changed.
Can be added points as much as wanted
Another line starts to draw from origin point and goes on every dots and finsih on the last.
added minimum, maxiumum and range points makes graph axis became striped
=> Line graph

engine/ui/gGUITreelist.cpp, engine/ui/gGUITreelist.h
=> gGUITreelist addElement function edited, drawContent function fixed, new functions added.

engine/ui/gGUIContextMenu.cpp, engine/ui/gGUIContextMenu.h, engine/ui/gGUIForm.cpp
I also added 3 new methods other than mouseReleased(int x, int y, int button)
1. getIsPressed() -> returns true if a menu item is pressed, otherwise returns false.
2. getItemTitle(itemNo) -> returns the title of the selected item
3. getContextMenuSize() -> returns the total number of context menu items
=> Context menu buttons are now functional.

engine/ui/gGUIContextMenu.cpp, engine/ui/gGUIContextMenu.h, engine/ui/gGUIForm.cpp, engine/ui/gGUIForm.h
showContextMenu() is now addContextMenu() and I changed the way we add seperators. When creating a menu item you send a bool value, if it's true a seperator will be added under the item.
=> Sub-menus can be added recursively but when you move your mouse on them they disappear.

engine/utils/gUtils.cpp, engine/utils/gUtils.h
2 new functions (gToFloat, gToDouble) are added to utils.cpp and utils.h files
=> gToFloat and gToDouble functions are added

engine/ui/gGUIListbox.cpp, engine/ui/gGUIListbox.h, engine/ui/gGUITreelist.cpp, engine/ui/gGUITreelist.h
=> gGUITreelist icon mode edited. gGUIListbox icon mode added, documentation added.

engine/ui/gGUINumberBox.cpp, engine/ui/gGUINumberBox.h
number box ui class is usable now
=> gGUINumberBox UI class finished

engine/ui/gGUIContextMenu.cpp, engine/ui/gGUIContextMenu.h
Fixed a bug where main menu was being drawn on top of sub-menus and I'm still trying to solve the problem where the sub-menu disappears if cursor is placed on it.
=> Menus are drawn in correct order now.

engine/ui/gGUITimebox.cpp, engine/ui/gGUITimebox.h
-> These functions, when the user increases or decreases, changes the value of the text box that he clicked on and ensures that the box is pressed.
-> In the mousePressed() function, whichever text box the user clicks on, the private function related to that box is enabled to work.
-> The names of the variables have been updated to make it more understandable.
-> By adding comment lines in some places, readability has been gained even over the header.
=> Added 3 private function for editing textboxes

engine/ui/gGUIContextMenu.cpp, engine/ui/gGUIContextMenu.h
- Fixed a bug where sub-menu seperators were twice as long than normally.
- Sub-menu borders are drawn correctly now.
- Sub-menus don't extend beyond screen now.
- All menus have shadows now.
=> Fixed some bugs and added shadows for the menu.

engine/core/gGUIActionManager.cpp, engine/ui/gGUIButton.cpp, engine/ui/gGUITreelist.cpp
=> gGUIActionManager TODO lines deleted. gGUITreelist and gGUIButton onGUIEvent added.

engine/CMakeLists.txt, engine/ui/gGUIContainer.cpp, engine/ui/gGUIContainer.h, engine/ui/gGUINotebookPanel.cpp, engine/ui/gGUINotebookPanel.h, engine/ui/gGUIPieGraph.h
addSizerToDeque and setSizerFromDeque functions added to gGUIContainer class for storing sizers more than one in gGUIContainer.
gGUINotebookPanel added.
Bug fix for gGUIPieGraph (shows infotext instantly at the beginning).
=> gGUINotebookPanel added, gGUIContainer and gGUIPieGraph updated.

engine/ui/gGUIForm.cpp, engine/ui/gGUIStatusBar.cpp, engine/ui/gGUIStatusBar.h
KeyPressed and keyReleased included for statusbar for use since textbox will need.
=> KeyPressed and keyReleased included for statusbar.

engine/ui/gGUILineGraph.cpp, engine/ui/gGUILineGraph.h
=> Y axis not drawing bug fixed, rangepoints now end at the end of the

engine/ui/gGUILineGraph.cpp, engine/ui/gGUIStatusBar.cpp, engine/ui/gGUIStatusBar.h
=> removed log lines from gGUILineGraph, added setText function to

engine/base/gBaseCanvas.cpp, engine/base/gBaseCanvas.h, engine/core/gAppManager.cpp, engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/gCamera.cpp
clearBackground execute moved to better optimisation and bugfix.
=> Canvas clearBackground moved.

engine/graphics/gTexture.cpp
Fixes https://github.com/GlistEngine/GlistEngine/issues/399
=> Fix magnification filtering

engine/base/gBaseCanvas.cpp, engine/base/gBaseCanvas.h, engine/core/gRenderer.cpp, engine/core/gRenderer.h
skybox interference with grid on 3d solved. methods names changed
=> skybox interference with grid on 3d solved. methods names changed

engine/core/gRenderer.cpp
now grid not reseting rendercolor's oldcolor. Some optimization applied as well.
=> now grid not reseting rendercolor's oldcolor. Some optimization applied

engine/core/gRenderer.cpp
Now grid lines can shown at any coordinates. as taking camera coordinates as referance
=> Now grid lines can shown at any coordinates. as taking camera

engine/graphics/gImage.cpp, engine/graphics/gImage.h, engine/utils/gFile.cpp, engine/utils/gUtils.cpp, engine/utils/gUtils.h
gImage::loadFromURL() function edited
=> gImage::loadFromURL() function edited

engine/base/gBaseGUIObject.cpp, engine/base/gBaseGUIObject.h, engine/ui/gGUIColorPicker.cpp, engine/ui/gGUIColorPicker.h, engine/ui/gGUIControl.cpp, engine/ui/gGUIImageButton.cpp, engine/ui/gGUIImageButton.h, engine/ui/gGUIListbox.cpp, engine/ui/gGUIListbox.h, engine/ui/gGUIMenubar.cpp, engine/ui/gGUIMenubar.h, engine/ui/gGUIResources.cpp, engine/ui/gGUIResources.h, engine/ui/gGUIToolbarButton.cpp, engine/ui/gGUIToolbarButton.h, engine/ui/gGUITreelist.cpp, engine/ui/gGUITreelist.h
gGUIResources is defined static
=> gGUIResources is defined static

engine/graphics/gModel.cpp, engine/graphics/gModel.h
Fix for gModel::rotateAround()
=> Fix for gModel::rotateAround()

engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/primitives/gRoundedRectangle.cpp, engine/graphics/primitives/gRoundedRectangle.h
Added gDrawRoundedRectangle to gRenderer
Closed #467
=> Added gDrawRoundedRectangle to gRenderer. Closed #467

engine/CMakeLists.txt
=> Some code comments

engine/CMakeLists.txt, engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/primitives/gCone.cpp, engine/graphics/primitives/gCone.h, engine/graphics/primitives/gCylinder.cpp, engine/graphics/primitives/gCylinder.h
Closed #468, closed #469; Added gDrawCylinder and gDrawCone to gRenderer and created their according classes.
=>  Added gDrawCylinder and gDrawCone to gRenderer

engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/primitives/gCone.cpp, engine/graphics/primitives/gCone.h, engine/graphics/primitives/gCylinder.cpp, engine/graphics/primitives/gCylinder.h, engine/graphics/primitives/gRoundedRectangle.cpp, engine/graphics/primitives/gRoundedRectangle.h
=> gDrawPrimitive function parameters edited in gRenderer

engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/primitives/gCone.h, engine/graphics/primitives/gCylinder.h
Deleted overloaded functions of gRectangle and gRoundedRectangle that had thickness parameter. Also changed default value of segmentnum for gCone and gCylinder from 64 to 32.
=> Deleted overloaded functions of gRectangle and gRoundedRectangle. Changed segmentnum for gCone and gCylinder to 32.

engine/ui/gGUIProgressBar.cpp, engine/ui/gGUIProgressBar.h
Revised gGUIProgressBar, added getters and setters for border size.
=> Revised gGUIProgressBar, added getters and setters for border size.

engine/ui/gGUIGraph.cpp
Changed gGUIGraph constants to scale with screen size.
=> Changed gGUIGraph constants to scale with screen size.

engine/ui/gGUIButton.cpp, engine/ui/gGUIButton.h
=> getButtonWidth() and getButtonHeight() functions added into gGUIButton

engine/ui/gGUIProgressBar.cpp, engine/ui/gGUIProgressBar.h, engine/ui/gGUITextbox.cpp, engine/ui/gGUITextbox.h
=> added backward text deletion with preceding text shifting and ctrl-z functionality

engine/ui/gGUIText.cpp, engine/ui/gGUIText.h
Text crash problem fixed.
Textaligment right and center fixed.
Line break splitting has been improved.
=> Text issues fixed

engine/ui/gGUIDropdownList.cpp, engine/ui/gGUITextbox.cpp, engine/ui/gGUITextbox.h
ListBox treelist menu now opens when clicked on textbox Fixed an issue that caused listbox treelist to receive click events even when its invisible
=> ListBox fixes

engine/base/gBaseGUIObject.cpp, engine/base/gBaseGUIObject.h, engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h, engine/ui/gGUIScrollable.cpp, engine/ui/gGUITextbox.cpp, engine/ui/gGUITextbox.h
- The text in the textboxes has been aligned to the right, left and center.
- When the enter key was pressed, the text was centered and displayed.
- When there is text in it, the cursor is adjusted to the alignment place.
- Fixed typing and scanning text where the cursor is.
- By pressing the arrow keys, the cursor moves, not the text.
- It was ensured that a textbox was created according to the size of the text, not exceeding the borders of the grid.
=> Text Alignment

engine/core/gGUIManager.cpp, engine/core/gGUIManager.h, engine/ui/gGUIGrid.cpp
- Fonts loaded (FreeSansBold.ttf, FreeSansOblique.ttf and FreeSansBoldOblique.ttf)
- Get desired font
- Assignment of iscellselected variable of cells
=> Load Fonts and Get Desired Font

engine/core/gGUIManager.cpp, engine/core/gGUIManager.h, engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h, engine/ui/gGUITextbox.cpp, engine/ui/gGUITextbox.h
- Obliques changed to italic.
- Each cell and textbox is drawn in the desired font.
- Regardless of the font of the engine, regular font is preferred for textbox and cells when the program is running.
=> Font Operations Completed

engine/base/gBaseGUIObject.cpp, engine/base/gBaseGUIObject.h, engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h, engine/ui/gGUITextbox.cpp, engine/ui/gGUITextbox.h
- Changed static alignment variable to enum.
- Cell-based alignment performed.
=> Text alignment is made to work separately for each cell

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- Added row selection feature.
- Added column selection feature.
- The selected row has been drawn.
- The selected column has been drawn.
- Added double-click feature to row and column so that the first elements are writable.
=> Row and column header selections set

engine/ui/gGUITextbox.cpp
=> Fix cursor not returning to previous line correctly during multiline

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- If alignment is not selected, alignment is done according to what is written (text or number)
=> Align according on entered value(String or Digit)

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- If there is no letter in the entered value, the leading + and unnecessary - are cleared.
- Digits are no longer accepted if there is more than one dat.
- If the ' sign is entered at the beginning of the sentence, it does not show it and does not delete the + and - signs.
=> Cell's showncontent has been edited and now negative values ​​can also be digits

engine/graphics/gImage.cpp, engine/graphics/gImage.h, engine/utils/gUtils.cpp, engine/utils/gUtils.h
Added Pixel Perfect Collision to the image.h
Added basic collision check to be used in PPC function to utils.h
=> Add Pixel Perfect Collision

engine/ui/gGUIText.cpp
Added skip to next line with "\n" tag.
=> Added skip to next line with "\n" tag.

engine/ui/gGUIText.cpp, engine/ui/gGUIText.h
=> lineh updated

engine/ui/gGUITextbox.cpp, engine/ui/gGUITextbox.h
=> text adjusts when textbox is expanded or shrinked in multiline

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- Instead of creating all cells at the start of the program, whichever is used and not created then it is created
=> Fixed performance loss if grid is too big

engine/ui/gGUINotebook.cpp, engine/ui/gGUINotebook.h
Improvements over existing notebook class
=> Improvements over existing notebook class

engine/ui/gGUIGrid.cpp
- If a row is double clicked that default cell height becomes the width of the column.
- If you double-click on a column, the longest text size in that column becomes the width of the column.
=> Added resize feature by double-clicking row/column ranges

engine/core/gRenderer.cpp, engine/core/gRenderer.h
Add ScreenShot Functionality which returns gImage 
Add Flipping Image functionality to flip the upside down image
=>  Add Screen Shot Functionality

engine/ui/gGUIGrid.cpp
- Fixed an error that occurred when trying to change the properties of a cell when no cell was selected.
=> Color of the selectedbox has changed and fixed some errors.

engine/graphics/gFont.cpp
This PR changes font data format to RGBA from LUMINANCE_ALPHA, which seems to cause issues for some android devices.
=> Fix font issue for Android

engine/ui/gGUILineGraph.cpp, engine/ui/gGUILineGraph.h
setPointValues() method created.
=> setPointValues()

engine/ui/gGUITable.cpp, engine/ui/gGUITable.h
according to the width of the table.
=> The new class gGUITable is ready for image minimizing and swapping files

engine/ui/gGUILineGraph.cpp, engine/ui/gGUILineGraph.h
void setPointValues(int lineIndex, float oldX, float oldY, float newX, float newY) function created.
void setPointValues(int lineIndex, int pointIndex, float newx, float newy); function updated to void setPointValues(int lineIndex, int pointIndex, float newX, float newY);
=> setPointValues functions created and updated.

engine/ui/gGUITable.cpp, engine/ui/gGUITable.h
=> ussulas libraries are deleted. Before get set methods are done Animated

engine/ui/gGUICheckbox.cpp, engine/ui/gGUICheckbox.h
setChecked function added
start value changed to false
=> setChecked function added

engine/ui/gGUIGrid.cpp
- "." placed between digits in number formatting. and space characters are also accepted.
- If the last character is comma or all the digits after the comma are equal 0, the decimal part is not displayed with the comma in number formatting.
- Added "YYYY, DD MMM" system to date formatting.
- "." instead of "-" and "/" characters in date formatting is placed.
- If the first character of the entered text corresponds to 39 in the ascii table, it is passed regardless of formatting conditions.
=> Added new features to number and date formatting

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- If an incorrect function is entered, the cell's showncontent is set to "Error".
=> Error message added

engine/ui/gGUIButton.cpp, engine/ui/gGUIButton.h, engine/ui/gGUICheckbox.h, engine/ui/gGUIDropdownList.h, engine/ui/gGUINumberBox.h, engine/ui/gGUISlider.h, engine/ui/gGUISwitchButton.h, engine/ui/gGUIToolbar.cpp, engine/ui/gGUIToolbar.h
Added multiple methods to the gGUIToolbar class.
=> Toolbar Update

engine/ui/gGUITable.cpp, engine/ui/gGUITable.h
have nice little anim for selected table and moved front of  table
=> Now we can set selected file num and get selected file num from code. We

engine/graphics/gFont.cpp, engine/graphics/gTexture.cpp
This PR fixes some texture filter issues where changing filter mode doesn't do anything.
=> Fix filtering issues

engine/ui/gGUIDropdownList.cpp, engine/ui/gGUIDropdownList.h, engine/ui/gGUINumberBox.cpp
The ispressed object was defined as bool and defined as the movement of the triangle on the button.
=> The triangle above the button in the dropdownlist moves together with the button.

engine/graphics/gFont.cpp, engine/graphics/gFont.h
=> Added getLineHeight() function

engine/CMakeLists.txt, engine/ui/gGUIForm.cpp, engine/ui/gGUIForm.h, engine/ui/gGUIFrame.cpp, engine/ui/gGUIText.cpp, engine/ui/gGUIText.h, engine/ui/gTooltipText.cpp, engine/ui/gTooltipText.h
In Text object vertical alignment was added, this works with Textbox objects.
=> VerticalAllignment

engine/ui/gGUIFrame.cpp, engine/ui/gGUIFrame.h
=> gGUIFrame constructor for Frame creation without registering to

engine/core/gAppManager.cpp, engine/graphics/gModel.h, engine/ui/gGUIGrid.h, engine/ui/gGUILineGraph.h
Also;
- Add missing includes that cause unknown symbol errors on Linux build.
=> Fix assertion error regarding setting window title before initialization

engine/ui/gGUITextbox.cpp
Textbox editable mode now activate at right textbox especially for multi textbox situation.
=> gGUITextBox Fix

engine/ui/gGUIToolbar.cpp, engine/ui/gGUIToolbarButton.cpp
This pull request fixes the issue where the toolbar was not fetching the correct color values.
=> Fix toolbar color fetching

engine/core/gRenderer.cpp, engine/graphics/gShader.cpp, engine/tools/ShaderToHeader.cpp
This PR fixes compile errors on Linux.
=> Fix linux compatability

engine/utils/gUtils.cpp, engine/utils/gUtils.h
This parameter is not being modified, it can be made const.
=> Made source parameter const in gReplaceAll

engine/graphics/gFont.cpp
To fix text misalignment issues, the function calculates the total width and adds extra character width. This ensures the text aligns correctly with screen edges and prevents overflow. The starting position is then adjusted based on this width.
=> gFont drawTextHorizontallyFlipped Fix

engine/base/gBaseGUIObject.cpp, engine/base/gBaseGUIObject.h, engine/core/gGUIManager.cpp, engine/core/gGUIManager.h, engine/ui/gGUIToolbar.cpp, engine/ui/gGUIToolbar.h, engine/ui/gGUIToolbarButton.cpp
Tema değiştirildiğinde toolbar ve toolbar button o temanın renklerini almıyordu (düzeltildi).
=> ToolBar Fix

engine/utils/gFile.cpp
This PR optimizes gFile::readFile function. This change makes reading big files much much more quicker.
=> Optimize gFile

engine/ui/gGUINavigation.cpp, engine/ui/gGUITooltipText.cpp, engine/ui/gGUITooltipText.h
Toolbar now stays at the bottom when the window size changes and tooltip window can be moved.
=> Toolbar position adjusts itself and tooltip's can be moved 

engine/ui/gGUIScrollable.cpp, engine/ui/gGUIScrollable.h
=> added a function to get vertical scroll.
