engine/core/gAppManager.cpp, engine/core/gAppManager.h, engine/core/gCanvasManager.cpp, engine/graphics/gTexture.cpp
**Problem:** In gTexture, data was being deleted by `delete`, which caused the engine crash on deleting the canvas that contained any object which inherits gTexture.
**Why:** The allocated memory on data is returned by stbi. Stbi uses `malloc` instead of `new` keyword. Therefore not dynamically allocating memory. `delete` can't be used to free the space that's allocated by malloc.
**Solution:**  Fixed by changing `delete data` to `stbi_image_free(data)`.
=> Canvas deletion fix

engine/base/gBaseApp.cpp, engine/base/gBaseApp.h, engine/core/gAppManager.cpp, engine/core/gAppManager.h, engine/core/gBaseWindow.cpp, engine/core/gBaseWindow.h, engine/core/gGLFWWindow.cpp, engine/core/gGLFWWindow.h
Implemented 2 versions of the main loop;
- First one that works with vsync, so there is no need for fixating the framerates
- Second one that limits the frames by implementing a special sleep function that uses [Welford's Algorithm](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford%27s_online_algorithm).
Without the Vsync, the CPU usage is ~9%, instead of pure spin-lock that causes around 15-100% CPU usage.
=> Game Loop framerate fixed

engine/ui/gGUIDialogue.cpp, engine/ui/gGUISizer.cpp
Additionally made getControl() of gGUISizer class to return null pointer when there's no control object in given row and column, which will be used for drag function of gGUIDialogue.
=> Set base64 icons for default title bar buttons

engine/core/gRenderer.cpp
This fixes an issue on macOS (or Apple's arm64 architecture) where everything appears fully dark.
=> Initialize missing shader variable

engine/graphics/gModel.cpp
This commit removes diffuse map checks when drawing the meshes of a model.
=> Fix an issue with model rendering

engine/media/gBaseSound.h, engine/media/gFmodSound.cpp, engine/media/gFmodSound.h
This commit contains a workaround for being unable to change the volume before playing and documentation changes.
=> Set volume of the sound after started playing

engine/graphics/gTexture.cpp
This commit fixes a rare (not so) SIGSEGV issue.
=> Initialize an uninitialized member which causes SIGSEGV

engine/core/gRenderer.cpp, engine/core/gRenderer.h, engine/graphics/gFog.cpp, engine/graphics/gFog.h, engine/graphics/gMesh.cpp
This pull request adds a linear mode to the fog, improves its documentation, and fixes the distance calculations. It also introduces the ability for developers to have multiple gFog classes with each of their own properties, which they can be switched between by enabling and disabling them as needed. Additionally, it makes the color shader sources string literals for ease of readability and editability.
If requested I can revert the string literals.
=> Improve fog system

engine/core/gGLFWWindow.cpp, engine/core/gGLFWWindow.h
This PR addresses the issue of inaccurate cursor placement on HiDPI screens, such as Apple Retina displays. If the framebuffer size is higher than the window size, it can result in incorrect coordinates being passed to the onMouseMoveEvent which , leading to misaligned cursor movements. Related to https://github.com/GlistEngine/GlistEngine/pull/491
Please let me know if there are any further improvements I can make to this implementation.
=> Correcting mouse movement on HiDPI screens for accurate cursor placement

engine/CMakeLists.txt, engine/core/backward.cpp, engine/core/backward.hpp
There were cases that C++ version was ignored in some platforms and not in others. 
Fixes C++ version definition. (C++17 definition inside CMAKE_CXX_FLAGS_RELEASE and CMAKE_CXX_FLAGS_DEBUG was ignored in some platforms, and caused compile errors where removed features is used.)
Removes duplicate definition of the same flags.
Removes unused -fuse-ld=gold flag.
Moved -DENABLE_BOOST_WORKAROUND=ON to set.
Updated backward library, old version was old and didn't have support for Aarch64 for Apple which led to compile errors on some Mac platforms.
Change -stdlib=c++ to -stdlib=libc++ which is Clang standard for defining it. (This change potentially fixes some of the visual errors with Eclipse on Mac)
gipOpenNN uses std::random_shuffle function that was removed in C++17, regarding to that C++ …
=> Fix compiler flags and update backward

engine/core/gBaseWindow.h, engine/core/gGLFWWindow.cpp
Related with https://github.com/GlistEngine/GlistEngine/pull/491 and https://github.com/GlistEngine/GlistEngine/pull/492. Adds missing multiplier to mouse_button_callback event.
=> Fix incorrect mouse position for mouse button events

engine/CMakeLists.txt
Added a new ENGINE_USE_SYMLINKS variable. If this is defined by GlistApp, it will indicate that our homebrew path is symlinks folder, not the Cellar folder. This variable is added to ensure compatibility with new engine versions and old GlistApp projects that define brew path to the Cellar folder.
=> Make LLVM_VERSION and OPENSSL_VER optional value

engine/ui/gGUIMenubar.cpp, engine/ui/gGUIMenubar.h, engine/ui/gGUIToolbarButton.cpp
-When an item is opened and the next is changed, the previous one does not close
- children of parent elements are opened automatically.
Problems solved
=> Fixed interaction of items in menubar

engine/ui/gGUIGrid.cpp, engine/ui/gGUIScrollable.cpp, engine/ui/gGUIScrollable.h
- Fixed the problem of not reaching the end of the grid even if scrolling is done to the end.
- Scrollbars align with the state of the title and by sending this if there is any extra space that needs to be left (marginx, marginy).
- The totalw variable is defined to work properly even if the screen size changes.
=> Fixed scrollbars in the grid

engine/ui/gGUIGrid.cpp
- If the cell is selected and text is typed without double-clicking, text can be written to the clean textbox.
=> Write text without double clicking on cells

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- Adjusted the location of the variables to make it easier to find.
- Value was sent to the undo function twice in copy operations. This has been fixed.
- The variable newgridboxw has been converted from int to float.
=> The codes was adjusted and bugs in the ctrl functions were fixed.

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- With enter, the grid is set to go down by the number of lines.
- If the current row is the last row and the enter key was pressed, it goes to the first row of the next column.
- If the cell is the last cell and the enter key was pressed, it goes to the first cell.
- After selecting a row, column or cell, multiple cell selection has been made by shift key + pressing any of the arrow keys.
- If multiple cells are selected, the transition between cells with enter is set to be inside the selected area.
- Clicking with the mouse or pressing one of the arrow keys while the shift key is not pressed will break the multi-selection.
- The green box representing the selected area is made to work properly according to multi-cell selection.
=> Select multiple cells with shift+arrow and switch cells with enter.

engine/core/gRenderer.cpp
This commit removes unnecessary glfw inlcude which causes Android build to fail.
=> Removed unnecessary glfw include. 

engine/ui/gGUIGrid.cpp
- ctrlzpressed or ctrlypressed variables would be true even if there was no undo or redo and they would stay true because the function didn't work, causing a crash in some cases.
- Wrong data was being kept if undo operation type was text.
=> Fixed bugs in undo and forward operations

engine/ui/gGUIGrid.cpp, engine/ui/gGUIGrid.h
- All cells are selected if clicking the upper left corner.
- Edited unnecessary large background drawing.
- The loop is broken when it comes to undrawn values after the row/column that needs to be drawn.
- If no change will be made for all of the selected cells in the control, instead of controlling all of the area, it is preferred the more efficient way.
=> Added function to select all cells and tweaks for better performance.

engine/core/gRenderer.cpp
This pull request fixes a problem with images appearing distorted. The issue occurs when displaying images with dimensions that aren't multiples of four. This can cause OpenGL to mishandle the images, leading to misaligned and improperly rendered visuals. Here's an example to help illustrate the problem:
**Issue Example:**
**Original Image:**
To solve this problem, the pull request aims to correct the misalignment and rendering issues. It ensures that images with dimensions not divisible by four are handled correctly. By changing unpack and pack alignments, OpenGL will properly handle these.
=> Set pack and unpack alignments to 1

engine/graphics/gImage.cpp
when defining checkPixelPerfectCollision(...){..} method, class name writed twice. I delete one.
=> Correcting method definition

engine/core/gRenderer.cpp, engine/graphics/gTexture.cpp, engine/graphics/gTexture.h
This PR addresses the performance issue with the existing `drawSub` function, which currently uploads vertex data to draw sub parts of a texture. With these changes, we optimize the function, making it 2-3 times faster by eliminating unnecessary vertex data uploads. This improvement aligns `drawSub` more closely with the performance of the `draw` function.
=> Enhance the performance of drawSub function

engine/graphics/primitives/gRectangle.cpp
The issue occurs while trying to draw a rectangle with lower opacity with alpha blending on.
Before the changes:
After the changes:
=> Fix gRectangle opacity issue

engine/core/gObject.cpp, engine/core/gObject.h, engine/core/gRenderer.cpp, engine/graphics/gMesh.cpp, engine/graphics/gMesh.h, engine/graphics/gModel.cpp, engine/graphics/gModel.h, engine/graphics/gNode.cpp, engine/graphics/gNode.h, engine/types/gColor.h
This PR optimizes bounding box generation, it's also updated when needed. Collision box updates are lazy evaluated, which means it will have no impact on performance if getBoundingBox is never called. With these changes frustum culling is now enabled by default. 
- Optimized bounding box generation, it can now be calculated hundreds of thousands of times per frame and have little to no impact on performance (depending on the vertex count and moved pieces).
- gObject now doesn't recalculate the exepath and assetsdir every time a new object is created. (This also includes gBoundingBox, which was a big performance hit because of the copying)
- Renderer now deletes lightsubo too.
- getBoundingBox now returns a const reference. 
- gColor asVec4 and asVec3 now const functions.
=> Frustum culling fixes and performance improvements

engine/graphics/gModel.cpp, engine/graphics/gVbo.cpp
This PR fixes an issue when `model.makeVertexAnimated();` called, gModel uses too much memory to crash the program.
=> Fix gModel high memory usage for macOS

engine/ui/gGUIScrollable.cpp
The problem with scrollbar was happening because of the miscalculations of totalw and totalh variables in the setDimensions function in the gGUIScrollable.cpp.
=> Scrollbar Fix

engine/ui/gGUIForm.cpp, engine/ui/gGUIPane.cpp, engine/ui/gGUISizer.cpp, engine/ui/gGUISizer.h
Extra parameters has added to setSlotPadding in gGUISizer
=> Vertical Slot Padding

engine/media/gFmodSound.cpp
gFmodSound deprecated  message is telling user at console as error message(class itself still working).
=> gFmodSound giving message to users now

engine/core/gAppManager.cpp
Fix stack trace error message when you close a running project.
=> gAppManager error fix(stack trace)
